### ISSUE TITLE
Font and Padding need a bit of adjusting and if possible rounding.

### ISSUE THREAD

**Issue by arsildo** [purogamer/Fluent-for-Steam#11]
![image](https://user-images.githubusercontent.com/51417052/154546846-65bc805e-82d0-4622-b1ee-ec8a6206a759.png)
![image](https://user-images.githubusercontent.com/51417052/154546892-cb31269f-ffa5-402f-829b-39a634106ede.png)
Font and Padding need a bit of adjusting and if possible rounding.

**Comment by purogamer** [comment]
yes, you're right, unfortunately due to steam limitations you can't round the context menus, but you can adjust the padding and font of that area. I'll keep it in mind for the next big update.

**Comment by purogamer** [comment]
![image](https://user-images.githubusercontent.com/87723899/155262024-8f4c48fd-6913-4bb7-b3f6-c3fb30d4cfde.png)

like this?
