### ISSUE TITLE
Invisible font in notifications.

### ISSUE THREAD

**Issue by arsildo** [purogamer/Fluent-for-Steam#12]
![image](https://user-images.githubusercontent.com/51417052/154547396-feec885b-6eb2-42de-9752-8361bf3bef8a.png)
![image](https://user-images.githubusercontent.com/51417052/154547606-105f004d-2e4b-438b-ada6-ee641420bb61.png)

**Comment by purogamer** [comment]
![Captura de pantalla 2022-02-22 183926](https://user-images.githubusercontent.com/87723899/155260559-3dc9d329-be98-42fd-8753-a789d85da5c5.png)
problem fixed, available when new release is released

**Comment by purogamer** [comment]
![Captura de pantalla 2022-02-22 183926](https://user-images.githubusercontent.com/87723899/155261712-73c52de1-46af-48d7-807d-77bb182dc134.png)
Fixed, available as soon as the next update is released. My mode of updating will not be little by little but an update will bring several changes.
