### ISSUE TITLE
No section about skins in new steam update

### ISSUE THREAD

**Issue by Vlad55432** [purogamer/Fluent-for-Steam#121]
Maybe I'm blind, or what, but there's no section about skins in new version steam.
![image](https://github.com/purogamer/Fluent-for-Steam/assets/78297186/51e946ff-7ba0-4ba2-b69e-cc545c9c4361)
I wonder it's steam issue, not for skin.

**Comment by RG007JM** [comment]
That's cause the new Steam app does not include Skins.

**Comment by Vlad55432** [comment]
> That's cause the new Steam app does not include Skins.

sad, but I found solution
I have downgraded steam
link below for tutorial (use "Post-2024: For the Unprepared" section) 
https://steamcommunity.com/sharedfiles/filedetails/?id=2967855237
![image](https://github.com/purogamer/Fluent-for-Steam/assets/78297186/0e048672-f6a7-422c-a0a9-aba4e5f534db)

**Comment by Vlad55432** [comment]
> That's cause the new Steam app does not include Skins.

sad, but I found solution
I have downgraded steam
link below for tutorial (use "Post-2024: For the Unprepared" section) 
https://steamcommunity.com/sharedfiles/filedetails/?id=2967855237
![image](https://github.com/purogamer/Fluent-for-Steam/assets/78297186/0e048672-f6a7-422c-a0a9-aba4e5f534db)
