### ISSUE TITLE
Can't choose it in Steam Settings

### ISSUE THREAD

**Issue by Sefohui** [purogamer/Fluent-for-Steam#124]
I don't know why but after I've extracted it to the "skins" folder in steam root folder and restart Steam I don't see the option to choose a skin in the interface settings. Is it the new steam style update messing it up?

**Comment by RG007JM** [comment]
Indeed it is, only the Patreon skin works with the new Steam Update.
Unfortunately the developer has been silent for 3 months

**Comment by Sefohui** [comment]
Yikes. Alright then I know there isn't anything I did wrong at least Thanks!
