### ISSUE TITLE
Support us button redirect is wrong

### ISSUE THREAD

**Issue by Lolihunter1337** [purogamer/Fluent-for-Steam#13]
![image](https://user-images.githubusercontent.com/17437302/154549735-b112200b-c76c-4312-a021-f35a2474b8f1.png)
![image](https://user-images.githubusercontent.com/17437302/154549769-75b9107d-9c9f-455f-9f94-f0b0eb9d9971.png)

**Comment by Lolihunter1337** [comment]
On that note this button doesn't seem to do anything
![image](https://user-images.githubusercontent.com/17437302/154549885-19856418-cf0b-4fd8-a3d2-51dc1684cb2b.png)

**Comment by purogamer** [comment]
oooh thanks, im stupid
