### ISSUE TITLE
Shift + Tab Menu Buttons

### ISSUE THREAD

**Issue by dakota724** [purogamer/Fluent-for-Steam#16]
Hello, I really like this theme and plan to use it for a while! I would like to request one thing in the shift + tab menu. 
I am requesting for there to be a "web browser" button in there somewhere, as it's a very useful button
Thank you for reading.
![image](https://user-images.githubusercontent.com/98860423/154604985-86312b7b-5d4a-4c75-b774-934ab8b3817d.png)

**Comment by purogamer** [comment]
the overlay is one of the things that needs to be finished, in future versions open the browser button, at the moment the way to access the browser is through the community hub or guides and then simply open a new tab

**Comment by purogamer** [comment]
extra comment: you have uninstalled Segoe UI Variable Text
