### ISSUE TITLE
Is it possible to implement the mica effect?

### ISSUE THREAD

**Issue by Void48** [purogamer/Fluent-for-Steam#23]
there's public Win32 API for Mica,Acrylic effects: DWMWA_SYSTEMBACKDROP_TYPE
don't know if it would be possible to add this

**Comment by purogamer** [comment]
no, unfortunately I think it is not possible since steam is a multiplatform program with its own language because it must work on MacOS, Linux and Windows. Therefore it would not be compatible with this new function or that is what I know, at least it cannot be done without hacking the program.
