### ISSUE TITLE
Most icons are not sharp at 4K 150% scaling

### ISSUE THREAD

**Issue by kuka69** [purogamer/Fluent-for-Steam#27]
Maybe updating the icons to higher resolutions would help. the min/max/close buttons are perfectly sharp, but most of the other icons that are part of the skin are not sharp.

**Comment by purogamer** [comment]
Continued to investigate if it's possible to add icons in 4k, but I'm afraid it doesn't work. So I will have to make a 4k version without steam scaling enabled.

**Comment by purogamer** [comment]
It has a parameter that is @2x in the name of the images and that allows you to add one more image with the appropriate resolution to rescale but that does not work with external skins

**Comment by purogamer** [comment]
so for now I'm going to leave the issue open while the 4k skin continues to be developed

**Comment by kuka69** [comment]
Sounds great, also I've compared the min/max/close buttons to other apps now and theyre also not sharp, so it really are all icons
<img width="141" alt="image" src="https://user-images.githubusercontent.com/83918321/155313992-534ea643-86ee-4d98-b1f0-aaa3fba3d64b.png">

**Comment by purogamer** [comment]
![image](https://user-images.githubusercontent.com/87723899/157325497-713017c3-2909-471a-a0f4-a3827495e53d.png)

WORK IN PROGRESS!
