### ISSUE TITLE
Display web address bar bugged

### ISSUE THREAD

**Issue by kmz27** [purogamer/Fluent-for-Steam#29]
This happens when I use the 'display web address bars when available'
(And if a page is loading there is a big red rectangle)

![image](https://user-images.githubusercontent.com/44536631/155623552-43a129da-a778-42d5-930f-be27236afb0e.png)

**Comment by Simon423** [comment]
Same problem here

**Comment by purogamer** [comment]
the error is already solved and in the next version it will come out!

**Comment by purogamer** [comment]
![image](https://user-images.githubusercontent.com/87723899/157163128-f0b94c36-16be-4afc-a166-e02faddd6600.png)
