### ISSUE TITLE
When Steam is started as a maximized window, it doesn't fully extend to the edge of the screen

### ISSUE THREAD

**Issue by Mintyseer** [purogamer/Fluent-for-Steam#30]
When Steam is started as a maximized window, the Steam window doesn't fully extend to the edge of the screen, and still retains rounded corners despite the fact that window behavior dictates sharp edges when an app is maximized. This issue is only resolved by spamming the maximize button several times. After a few seconds the window is maximized like normal.

How it currently is:
![Screenshot 2022-03-04 215452](https://user-images.githubusercontent.com/94312236/156865131-66d1033f-d145-4734-bce0-12527037b4f5.png)

How it should be:
![Screenshot 2022-03-04 215507](https://user-images.githubusercontent.com/94312236/156865135-af44b08f-2a1a-4b61-a404-7823b68e6f39.png)

**Comment by purogamer** [comment]
haha that mistake is not mine. that's valve's fault i can't solve problems that have to do with how valve handles compatibility with windows.
