### ISSUE TITLE
Start SteamVR Button Glitched

### ISSUE THREAD

**Issue by Firexik** [purogamer/Fluent-for-Steam#31]
The button seems to be colliding with a "Button" text.
The button also seems to be always a little bit more gray than the others (My mouse is not present on the button in the included screenshot).

Screenshot: https://i.imgur.com/I6hkviy.png

**Comment by purogamer** [comment]
thanks for the report that this solution, with the next update will be fixed. In the meantime you can check development news on my patreon.com/Fluent-for-Steam
