### ISSUE TITLE
[Feature Request] Request to extend black background theme to library section as well :)

### ISSUE THREAD

**Issue by AmitKhare1088** [purogamer/Fluent-for-Steam#34]
Such an awesome theme. Request to extend black background theme to library as well.
Thank you for creating such an awesome theme :)

**Comment by purogamer** [comment]
SCREENSHOT PLS

**Comment by AmitKhare1088** [comment]
![1](https://user-images.githubusercontent.com/15840367/161670095-2648384c-5956-4509-9121-786a8860b005.png)
![2](https://user-images.githubusercontent.com/15840367/161670098-bb29abb3-9430-4a27-beec-c5e81d4a89b0.png)
Image 1 has black background (store section)
Image 2 library is grey (original steam color)

Feature request - Can library section have black background too? 

Thank you :)

**Comment by purogamer** [comment]
ah i understand, its is posible with [THIS PATCH ](https://github.com/AikoMidori/steam-library)
