### ISSUE TITLE
Steam Guard lock logo only shown text "Label"

### ISSUE THREAD

**Issue by KucingMangkal** [purogamer/Fluent-for-Steam#35]
![image](https://user-images.githubusercontent.com/34916612/161743181-8321195a-d018-470d-9cc7-ed62d6266678.png)

dunno what's the problem, it should be like this rite.
![image](https://user-images.githubusercontent.com/34916612/161743327-e9c98d00-2a76-41d4-bd18-97a8e37150dc.png)

prolly only just me

**Comment by xlifi** [comment]
It not only shows "Label" instead of image, but it doesnt fit the code
![изображение](https://user-images.githubusercontent.com/70767436/167524523-5693ef2f-d457-4c1b-aaa9-1f7b1d648b3c.png)
