### ISSUE TITLE
Add option for adding product key to account

### ISSUE THREAD

**Issue by PhantomGamers** [purogamer/Fluent-for-Steam#38]
Maybe I'm just not seeing it and it already exists somewhere but I can't find it

**Comment by RG007JM** [comment]
> Maybe I'm just not seeing it and it already exists somewhere but I can't find it
 @PhantomGamers 

If you click on the plus button, you'll see an option called "Activate a Steam on Product"
![image](https://user-images.githubusercontent.com/53452689/163539020-94abd570-fb6a-4bb0-a62c-080e7415cf98.png)

(Sorry for the bad format, this is the first reply on Github for me so I really don't know how to mention you)

**Comment by PhantomGamers** [comment]
Ah I don't know how I missed that, thank you so much!!!

And you did fine, you don't really have to mention people in issues that they are a part of because they get notifications by default :)
