### ISSUE TITLE
Black text over black text in the "Notification" menu

### ISSUE THREAD

**Issue by RG007JM** [purogamer/Fluent-for-Steam#40]
As you can see, the text is the same color as the background.
(If you hover over it you can see the text)
![image](https://user-images.githubusercontent.com/53452689/163469176-2d0b7c48-f488-421c-8aba-1f46b1080a28.png)

**Comment by purogamer** [comment]
will be fixed with new update

![image](https://user-images.githubusercontent.com/87723899/163734365-1c067892-02bf-40d1-a1c5-7d9c6c193645.png)
