### ISSUE TITLE
Cannot veiw settings

### ISSUE THREAD

**Issue by totallygeekdom** [purogamer/Fluent-for-Steam#43]
When opening the settings panel, it opens in a very small window that cannot be moved or resized. 
![image](https://user-images.githubusercontent.com/76084843/164452289-544d7667-a33c-41a7-8579-b21626d28c00.png)

**Comment by purogamer** [comment]
https://www.patreon.com/posts/fluent-for-steam-63282069 try download this version

**Comment by totallygeekdom** [comment]
> https://www.patreon.com/posts/fluent-for-steam-63282069 try download this version

steam does not recognize the version
