### ISSUE TITLE
No Mica

### ISSUE THREAD

**Issue by corriganc** [purogamer/Fluent-for-Steam#47]
To be fully in-keeping with Windows 11 design principles, the titlebar and sidebar should utilse the Mica material.

Microsoft docs: https://docs.microsoft.com/en-us/windows/apps/design/style/mica

Github project enabling Mica for other apps: https://github.com/MicaForEveryone/MicaForEveryone

Otherwise, great work! :)

**Comment by purogamer** [comment]
Unfortunately, as it is a program that must work on different operating systems, it does not use xml libraries because it is impossible to apply it in real time.
