### ISSUE TITLE
Missing maximize button

### ISSUE THREAD

**Issue by Makezu90** [purogamer/Fluent-for-Steam#48]
![steam_9EqkTLd9ld](https://user-images.githubusercontent.com/89158176/169844510-d2cee32d-a06b-4c87-9c8c-76a4cfecbe76.png)

**Comment by corylowry12** [comment]
If you just clone the repo and copy and paste the files into the steam/skins directory the issue will be fixed. If you just download the latest release, that bug still exists. Thats how i fixed it missing the button.
