### ISSUE TITLE
[Feature Request] Steam balance

### ISSUE THREAD

**Issue by realnexon** [purogamer/Fluent-for-Steam#50]
Hello. Is there any way to see our Steam Balance Without clicking our Username/Icon? If not can you make it visible?

**Comment by purogamer** [comment]
![image](https://user-images.githubusercontent.com/87723899/171078345-14db3f02-cbc2-466f-8477-dc61a7c1f072.png)
in next update

**Comment by Benisgo** [comment]
When is the next update? The current version has a lot of issues at the moment
