### ISSUE TITLE
Releases are empty

### ISSUE THREAD

**Issue by Lolihunter1337** [purogamer/Fluent-for-Steam#6]
Download the latest version of the skin, by clicking https://github.com/purogamer/Fluent-for-Steam/releases leads to no release :v

**Comment by Reynbow** [comment]
Yep, nothing there at all. No way to download.

**Comment by Lolihunter1337** [comment]
@Reynbow 
![image](https://user-images.githubusercontent.com/17437302/154468155-c8f444f8-a295-4ba9-adce-ae0ff5bb23e6.png)
you can click on code and download the zip

**Comment by purogamer** [comment]
resolved
