### ISSUE TITLE
Activity popup text not visible

### ISSUE THREAD

**Issue by RZR7332** [purogamer/Fluent-for-Steam#62]
After updating to the new release earlier, the activity popup (e.g. when a friend launches a game) does not display any text:

![image](https://user-images.githubusercontent.com/97453016/179234783-d7dc5840-9f16-43cf-b121-e472e1ceb4d3.png)

**Comment by purogamer** [comment]
Thanks! working on solving it.

**Comment by purogamer** [comment]
Thanks! working on solving it.
