### ISSUE TITLE
Full name showcase

### ISSUE THREAD

**Issue by Ali811G** [purogamer/Fluent-for-Steam#8]
This is not much of an issue and more of a suggestion, is there any way to make it so that in the top right corner it shows your full username and not a cutout version of it? like my username is 『A L I 8 1 1』 알리 but it only shows 『A L I 8 ... and i want it to show the full thing... you dont have to change it for everyone if there is a way i can modify mine to show my full name im good with that too :) Thank you for the amazing skin already loving it <3

**Comment by purogamer** [comment]
that and other details are being resolved, which will be solved in the next version
