### ISSUE TITLE
Regarding downloading and installing fluent for steam

### ISSUE THREAD

**Issue by milindgoel15** [purogamer/Fluent-for-Steam#88]
New to this repo,

Are we supposed to download whole source code provided in the releases section and putting the folder into Steam/Skins? or i am missing something.

**Comment by OriginalSwayze** [comment]
Download the Source code and extract the folder then put the folder into the "skins" folder if one doesn't exist simply make one 

Hope this helps

**Comment by milindgoel15** [comment]
Yea was just confirming. 
So to make it auto-updated whenever there is a new release, i cloned the repo using git. The next time I just need to fetch the new changes and voila.

Yes, indeed, the best theme for steam
