### ISSUE TITLE
0.4.4.2fix breaks music player

### ISSUE THREAD

**Issue by Wimbit** [purogamer/Fluent-for-Steam#90]
With default skin:
![image](https://user-images.githubusercontent.com/102480418/193881363-76f3c7b6-ea0d-4dbe-8455-a965d7234735.png)

With Fluent:
![image](https://user-images.githubusercontent.com/102480418/193881410-8c17a669-36d8-40db-8bc0-95f3aa5aedbc.png)

**Comment by RG007JM** [comment]
There's already an open issue that talks exactly about this  [Issue#70](https://github.com/purogamer/Fluent-for-Steam/issues/70)
