### ISSUE TITLE
Friends popup still the steam default

### ISSUE THREAD

**Issue by LaurensTheDev** [purogamer/Fluent-for-Steam#96]
In the overlay the friends popup is still the ugly default. Is this gonna be updated?

**Comment by RG007JM** [comment]
This is only a Steam skin, so it won't impact neither the Library, neither the Friends popup.
I recommend you try [SFP](https://github.com/PhantomGamers/SFP), with these files in the zip.
[Themes.zip](https://github.com/purogamer/Fluent-for-Steam/files/10815899/Themes.zip)

**Comment by LaurensTheDev** [comment]
Thanks
